### ISSUE TITLE
IllegalArgumentException from EsqlSquidSensor 

### ISSUE THREAD

**Issue by mresetar** [EXXETA/sonar-esql-plugin#28] opened 2018-01-03 13:05 UTC
Hi, 

I'm having problems to run the plugin agianst fairly simple project. I've fixed 2 cases which have thrown NPE exception (happy to share those) but here is the latest one that I'm not sure how to fix. 

Environment:
- Win2k12 64bit
- IIB 10.0.0.10
- Java 8
- Maven 3.5.2

What I'm doing? 
1. I've added msgflow (sonar-msgflow-plugin-1.1.1) to Sonar 6.7.1
2. I've cloned this repo and package it
3. Copied esql-plugin-2.3.0-SNAPSHOT.jar to Sonar plugins
4. I have a simple IIB v10 project with pom.xml 
5. I'm running `mvn -X -e clean install sonar:sonar` on the project (command line)

On the file below file (ProcessMessage.sql) IAE is thrown. File is shared in [this gist](https://gist.github.com/mresetar/b7db78ebae610ecb4ccc925a42e9d83b). At line 12 it has exactly 23 chars. Not sure why and how 85 was calculated. 

```
Caused by: java.lang.IllegalArgumentException: 85 is not a valid line offset for pointer. File util/ProcessMessage.esql has 23 character(s) at line 12
    at org.sonar.api.internal.google.common.base.Preconditions.checkArgument (Preconditions.java:145)
    at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid (DefaultInputFile.java:312)
    at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer (DefaultInputFile.java:246)
    at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange (DefaultInputFile.java:262)
    at com.exxeta.iss.sonar.esql.EsqlSquidSensor.newLocation (EsqlSquidSensor.java:263)
    at com.exxeta.iss.sonar.esql.EsqlSquidSensor.savePreciseIssue (EsqlSquidSensor.java:250)
    at com.exxeta.iss.sonar.esql.EsqlSquidSensor.saveFileIssues (EsqlSquidSensor.java:240)
    at com.exxeta.iss.sonar.esql.EsqlSquidSensor.scanFile (EsqlSquidSensor.java:228)
    at com.exxeta.iss.sonar.esql.EsqlSquidSensor.analyse (EsqlSquidSensor.java:162)
    at com.exxeta.iss.sonar.esql.EsqlSquidSensor.analyseFiles (EsqlSquidSensor.java:137)
    at com.exxeta.iss.sonar.esql.EsqlSquidSensor.execute (EsqlSquidSensor.java:317)
```

**Comment by ThomasPohl** [comment] 2018-01-03 21:40
Thanks for your bug report. 
I will try to reproduce the problem and hopefully fix it.

If you could share the two NPE fixes that would be great.

**Comment by ThomasPohl** [comment] 2018-01-04 07:47
Hi,
I was not able to reproduce you problem. From the stacktrace I can tell, that there must be an error in one of the checks/rules. Maybe one of the most recent changes fixed this issue. 

Can you retest with the latest sources?

**Comment by mresetar** [comment] 2018-01-04 09:46
Hi, I've reset my local repository to ` * |   1909d80 (HEAD -> master, tag: 2.2.0, origin/master) Merge branch 'release/2.2.0'`  and rebuild. I don't get any NPE exceptions this time and analysis run fine. 
The sample project is now on my GitHub [here](https://github.com/mresetar/monitoring-sample). 

Previously I did get some NPEs which I was trying to fix wit the following fixes.
- [This one](https://github.com/mresetar/sonar-esql-plugin/commit/9b6e16ba15e4172ef50830f2512019361d9bee89) was caused by parentFile being null. I'm curious why the pattern `parentFile.getName().matches("^[a-zA-Z]*(_App_v|_Lib_v)[0-9]")` is used? In my case there is no App_v or Lib_v ending in project name. Because parntFile was null I added the fix to look for .project file. I don't know was that fine or not. But fix is not working as expected with multimodule projects. 
- [Second one](https://github.com/mresetar/sonar-esql-plugin/commit/9a595e2e6fe76e553ebd300684dfeb53da9241b0) is probably connected with first fix not working as expected. 
I guess you can ignore this ones for now. 
I've made also 2 changes to gitignore and gitattributes you may want to check out.

Thanks for the plugin!

Miro

**Comment by ThomasPohl** [comment] 2018-01-04 11:16
- The pattern "^[a-zA-Z]*(_App_v|_Lib_v)[0-9]" was introduced by the original author of the PropagateConsistencyCheck. I guest he always names his project-directories that way. I changed it because it wasn't generic enough for me.
- I added your second change to the current develop branch. These checks were missing.
- I did not add your gitattribut changes, because some test-cases rely on the linefeed conversion. If the linefeed changes depending on the os, these test-cases won't work. It would be a possibility to add the conversion only for some specific files. Did you have any trouble with the conversion?

**Comment by mresetar** [comment] 2018-01-04 12:04
- Why project pattern is even needed? Could it be removed alltogether?  I can see it can be a problem to rely on the pattern. 
- Ok. I guess they might have been. 
- For some reason ESQLs were converted in my case. Treating them as binary did the trick but yours line is better. Ignore this one.

**Comment by ThomasPohl** [comment] 2018-01-04 12:06
Great! Thanks for your input. I will close the issue then.

**Closed by ThomasPohl** 2018-01-04 12:06 UTC
Labels: bug
