### ISSUE TITLE
Nested comments in ESQL will cause parse error

### ISSUE THREAD

**Issue by essiwkw** [EXXETA/sonar-esql-plugin#100] opened 2018-07-20 05:05 UTC
Nested comments in ESQL (which is syntactically correct) will cause parse error, below is example (nested comments on line 59):

13:00:32.063 ERROR: Parse error at line 60 column 13:

50:   -- Section 2
51:   DECLARE refToInvoice REFERENCE TO "InputRoot"."XMLNSC"."SaleEnvelope"."Sal
eList"."Invoice";
52:   IF lastmove(refToInvoice) THEN
53:    SET Variable2 = refToInvoice."Initial"[1] ||refToInvoice."Initial"[2]; --
 append the two initials together
54:    SET Variable3 = refToInvoice."Surname";
55:   ELSE
56:    /*
57:        if fields can not be found in message then set to a default value.
58:        An alternative to this would be throw an exception.
59:        /** nested comments **/
60:        This could be done using the ESQL:
                ^
61:           THROW EXCEPTION MESSAGE 3000 ;
62:    */
63:    -- Section 3
64:    SET Variable2 = 'default';
65:       SET Variable3 = 'default';
66:   END IF;
67:
68:   /*
69:    Use these Variables to select the queue manager name and the queue name f
rom the database.
70:    It is important to note that this sample only ever returns

**Comment by ThomasPohl** [comment] 2018-07-23 07:39
Hi, that's a duplicate of #96

**Closed** 2020-01-05 15:13 UTC
Labels: bug, duplicate, fixed - included in next release
