### ISSUE TITLE
Error while scanning Esql code

### ISSUE THREAD

**Issue by tarekhammad1982** [EXXETA/sonar-esql-plugin#146] opened 2023-01-17 10:49 UTC
Hi All,

I Am getting the following error when trying to scan Esql code

ERROR: Unable to analyse file: file:///C:/SourceCodeScan/esb-procure-to-pay-services-Develop@af9a8cdd2e8/InitiativeContractsInquiry/InitiativeContractsInquiry/InitiativeContractsInquiryRq.esql
java.lang.IllegalArgumentException: Overlapping symbol declaration and reference for symbol at Range[from [line=48, lineOffset=35] to [line=48, lineOffset=44]]
        at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
        at org.sonar.api.batch.sensor.symbol.internal.DefaultSymbolTable$DefaultSymbol.newReference(DefaultSymbolTable.java:110)
        at org.sonar.api.batch.sensor.symbol.internal.DefaultSymbolTable$DefaultSymbol.newReference(DefaultSymbolTable.java:104)
        at com.exxeta.iss.sonar.esql.highlighter.HighlightSymbolTableBuilder.addReference(HighlightSymbolTableBuilder.java:58)
        at com.exxeta.iss.sonar.esql.highlighter.HighlightSymbolTableBuilder.highlightSymbol(HighlightSymbolTableBuilder.java:51)
        at com.exxeta.iss.sonar.esql.highlighter.HighlightSymbolTableBuilder.build(HighlightSymbolTableBuilder.java:39)
        at com.exxeta.iss.sonar.esql.EsqlSensor.highlightSymbols(EsqlSensor.java:328)
        at com.exxeta.iss.sonar.esql.EsqlSensor.scanFile(EsqlSensor.java:221)

---------------
while the line of code mentioned in the file is normal code for functions, which is
**CREATE FUNCTION DecryptPassword(IN Encrypted CHAR)**
	RETURNS CHARACTER
	LANGUAGE JAVA
	EXTERNAL NAME "Password.decrypt";

![image](https://user-images.githubusercontent.com/122876688/212879833-250bbd70-0634-4ed2-8cd1-4e27d0c93a4f.png)

**Comment by christoph-weiss-ibm** [comment] 2023-08-11 17:19
Hi @tarekhammad1982: 
the same issue is already mentioned here: https://github.com/EXXETA/sonar-esql-plugin/issues/141 
Unfortunately I am currently running into the same issue.
Thus I asked in the other issue if there are any updates / information on the possible root cause.

**Comment by ThomasPohl** [comment] 2023-10-08 07:44
I finally found the problem. I had saved the declaration twice (No clue why that was no problem in previous versions) Will be fixed in next release

**Comment by ThomasPohl** [comment] 2023-10-08 08:37
@tarekhammad1982 @christoph-weiss-ibm  Please check if release [3.4.0-RC2](https://github.com/EXXETA/sonar-esql-plugin/releases/tag/untagged-daaa377877fb90843836) fixes the problem for you

**Closed** 2023-10-16 07:13 UTC
Labels: fixed - included in next release
